# Generated by Django 5.0.4 on 2024-05-01 17:02

import django.db.models.deletion
import social_media.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostponedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        upload_to=social_media.helpers.upload_image_file_path
                    ),
                ),
                ("postponed_at", models.DateTimeField()),
                ("published", models.BooleanField(default=False)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postponed_posts",
                        to="social_media.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-postponed_at",),
            },
        ),
    ]
